name: Build & Deploy Domain Branches

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      branches:
        description: 'Branches (comma-separated) to build/deploy'
        required: false
        default: 'sity.top'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine branches to process
        id: pick
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "BRANCHES=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "BRANCHES=${{ github.event.inputs.branches }}" >> $GITHUB_ENV
          fi

      - name: Build & Deploy per branch
        run: |
          IFS=',' read -ra LIST <<< "$BRANCHES"
          for br in "${LIST[@]}"; do
            echo "→ Processing $br"
            git checkout $br
            # Use npm install since no lock file is committed
            npm install --no-audit --no-progress
            npm run build
            # Inject GitHub update headers into style.css
            sed -i '/^GitHub Theme URI:/d' style.css
            sed -i '/^GitHub Branch:/d' style.css
            sed -i "/^Tags:/a GitHub Theme URI: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY\nGitHub Branch: ${br}" style.css
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            if ! git diff --quiet style.css; then
              git commit -am "Add GitHub update headers"
              git push origin HEAD:$br
            fi
            # Deployment commands could go here
          done